#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
fix_profit_loss_display.py

Post-process generated stock-report HTML files and normalize profit-taking / stop-loss display.

Fixes examples:
- 익절: +3%(60) / +5%(20) / +10(20)
  -> 익절: +3%(60%) / +5%(20%) / +10%(20%)

- 손절: 2% / 4% / 6 / 80% / 10% / 10%
  -> 손절: -2%(80%) / -4%(10%) / -6%(10%)

Why post-process:
- /mobile/ and /details/legacy_top15.html can be generated by different scripts.
- Final UI rebuild can overwrite earlier fixes.
- Running this script after all HTML generation fixes the final committed files.
"""

from __future__ import annotations

from pathlib import Path
import re
from typing import Iterable

TARGET_FILES = [
    Path("docs/mobile/index.html"),
    Path("docs/details/legacy_top15.html"),
    Path("docs/index.html"),
]

# Also scan details/mobile pages broadly because the same formatter can appear elsewhere.
GLOB_TARGETS = [
    "docs/details/*.html",
    "docs/mobile/*.html",
]


def fmt_num(value: str) -> str:
    value = str(value or "").strip().replace(",", "")
    try:
        n = float(value)
    except Exception:
        return value

    if abs(n - int(n)) < 1e-9:
        return str(int(n))

    return f"{n:.2f}".rstrip("0").rstrip(".")


def extract_nums(text: str) -> list[str]:
    return re.findall(r"[+-]?\d+(?:\.\d+)?", text or "")


def extract_pairs(text: str) -> list[tuple[str, str]]:
    """Extract values already written as 3%(60), +5%(20%), etc."""
    pairs: list[tuple[str, str]] = []

    for m in re.finditer(
        r"([+-]?\d+(?:\.\d+)?)\s*%?\s*\(\s*([+-]?\d+(?:\.\d+)?)\s*%?\s*\)",
        text or "",
    ):
        pairs.append((m.group(1), m.group(2)))

    return pairs


def format_profit(segment: str) -> str | None:
    original = segment
    pairs = extract_pairs(segment)

    if pairs:
        out = []
        for rate, weight in pairs[:3]:
            out.append(f"+{fmt_num(rate).lstrip('+-')}%({fmt_num(weight).lstrip('+-')}%)")
        return " / ".join(out) if out else None

    nums = extract_nums(segment)

    if len(nums) >= 6:
        rates = nums[:3]
        weights = nums[3:6]
        return " / ".join(
            f"+{fmt_num(rate).lstrip('+-')}%({fmt_num(weight).lstrip('+-')}%)"
            for rate, weight in zip(rates, weights)
        )

    if len(nums) >= 3:
        rates = nums[:3]
        return " / ".join(f"+{fmt_num(rate).lstrip('+-')}%" for rate in rates)

    if len(nums) == 1:
        return f"+{fmt_num(nums[0]).lstrip('+-')}%"

    return None


def format_stop(segment: str) -> str | None:
    pairs = extract_pairs(segment)

    if pairs:
        out = []
        for rate, weight in pairs[:3]:
            out.append(f"-{fmt_num(rate).lstrip('+-')}%({fmt_num(weight).lstrip('+-')}%)")
        return " / ".join(out) if out else None

    nums = extract_nums(segment)

    # Broken form: 2% / 4% / 6 / 80% / 10% / 10%
    # Means: stop rates = 2,4,6 and weights = 80,10,10
    if len(nums) >= 6:
        rates = nums[:3]
        weights = nums[3:6]
        return " / ".join(
            f"-{fmt_num(rate).lstrip('+-')}%({fmt_num(weight).lstrip('+-')}%)"
            for rate, weight in zip(rates, weights)
        )

    if len(nums) >= 3:
        rates = nums[:3]
        return " / ".join(f"-{fmt_num(rate).lstrip('+-')}%" for rate in rates)

    if len(nums) == 1:
        return f"-{fmt_num(nums[0]).lstrip('+-')}%"

    return None


def normalize_html_text(html: str) -> tuple[str, int]:
    changed = 0

    # Boundaries: stop before another label, tag start/end, or newline.
    # This intentionally works as a final HTML text post-processor.
    profit_pattern = re.compile(
        r"(익절\s*[:：]\s*)(.*?)(?=(?:손절\s*[:：]|<br\b|</|<|\r|\n))",
        flags=re.IGNORECASE | re.DOTALL,
    )

    stop_pattern = re.compile(
        r"(손절\s*[:：]\s*)(.*?)(?=(?:익절\s*[:：]|<br\b|</|<|\r|\n))",
        flags=re.IGNORECASE | re.DOTALL,
    )

    def repl_profit(m: re.Match) -> str:
        nonlocal changed
        label = m.group(1)
        segment = m.group(2)
        formatted = format_profit(segment)

        if formatted and formatted != segment.strip():
            changed += 1
            return label + formatted

        return m.group(0)

    def repl_stop(m: re.Match) -> str:
        nonlocal changed
        label = m.group(1)
        segment = m.group(2)
        formatted = format_stop(segment)

        if formatted and formatted != segment.strip():
            changed += 1
            return label + formatted

        return m.group(0)

    html = profit_pattern.sub(repl_profit, html)
    html = stop_pattern.sub(repl_stop, html)

    return html, changed


def iter_target_files() -> Iterable[Path]:
    seen: set[Path] = set()

    for path in TARGET_FILES:
        if path.exists() and path.is_file():
            resolved = path.resolve()
            if resolved not in seen:
                seen.add(resolved)
                yield path

    for pattern in GLOB_TARGETS:
        for path in sorted(Path(".").glob(pattern)):
            if path.exists() and path.is_file():
                resolved = path.resolve()
                if resolved not in seen:
                    seen.add(resolved)
                    yield path


def main() -> int:
    total_files = 0
    changed_files = 0
    total_replacements = 0

    for path in iter_target_files():
        total_files += 1

        try:
            html = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            html = path.read_text(encoding="utf-8-sig", errors="replace")

        fixed, replacements = normalize_html_text(html)

        if replacements > 0 and fixed != html:
            path.write_text(fixed, encoding="utf-8")
            changed_files += 1
            total_replacements += replacements
            print(f"✅ fixed {path} replacements={replacements}")

    print(
        f"✅ Profit/Loss display normalization complete: "
        f"scanned_files={total_files}, changed_files={changed_files}, replacements={total_replacements}"
    )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
